apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - nodePort: 30005
      port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app

