apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec: 
  replicas: {{ .Values.backendResult.replicaCount }}
  selector: 
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: {{ .Values.backendResult.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.backendResult.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.backendResult.postgresPassword }}

